apiVersion: harness.io/v1
kind: Component
type: service
identifier: teamk_kroger455ip1
name: teamk_kroger455ip1
owner: group:account/Kroger
orgIdentifier: kroger455org
projectIdentifier: kroger455ip1
spec:
  lifecycle: experimental
metadata:
  description: Description_of_the_app_being_scaffolded
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/harnessworkshop/teamk_kroger455ip1/blob/main
    backstage.io/source-location: url:https://github.com/harnessworkshop/teamk_kroger455ip1
  links:
  - title: Website
    url: https://harness.io
  tags:
  - my-sample
